# Generated by Django 3.1.3 on 2020-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
