# Generated by Django 3.1.3 on 2020-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20201201_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_carrito',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
