# Generated by Django 3.1.3 on 2020-12-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20201201_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
