# Generated by Django 3.1.3 on 2020-11-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0002_auto_20201124_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
